teams:
  Manchester United:
    h_ranges: [[0, 10], [160, 180]]
    s_min: 100
    v_min: 100
    primary_color: [255, 0, 0]
    secondary_color: [200, 0, 0]
  
  Manchester City:
    h_ranges: [[85, 110]]
    s_min: 80
    v_min: 120
    primary_color: [0, 150, 255]
    secondary_color: [0, 100, 200]
  
  Liverpool:
    h_ranges: [[0, 10], [160, 180]]
    s_min: 150
    v_min: 150
    primary_color: [220, 0, 0]
    secondary_color: [180, 0, 0]
  
  Chelsea:
    h_ranges: [[100, 130]]
    s_min: 120
    v_min: 120
    primary_color: [0, 0, 255]
    secondary_color: [0, 0, 200]
  
  Norwich City:
    h_ranges: [[35, 50]]
    s_min: 100
    v_min: 100
    primary_color: [0, 255, 255]
    secondary_color: [0, 200, 200]
  
  Brazil:
    h_ranges: [[20, 40]]
    s_min: 120
    v_min: 150
    primary_color: [0, 200, 150]
    secondary_color: [0, 150, 100]
  
  Referee:
    h_ranges: [[0, 180]]
    s_max: 40
    v_min: 200
    primary_color: [0, 215, 255]
    secondary_color: [0, 180, 220]

jersey_colors:
  - name: "Red"
    h_ranges: [[0, 10], [160, 180]]
    s_min: 100
    v_min: 100
  
  - name: "Blue"
    h_ranges: [[100, 130]]
    s_min: 80
    v_min: 100
  
  - name: "Yellow"
    h_ranges: [[35, 50]]
    s_min: 100
    v_min: 100
  
  - name: "Green"
    h_ranges: [[50, 80]]
    s_min: 100
    v_min: 100
  
  - name: "White"
    h_ranges: [[0, 180]]
    s_max: 40
    v_min: 200